name: kef_ls50w2_client
description: Connect to and control your KEF LS50 Wireless 2
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  json_annotation: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

